-------------------------------------------------
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Template to create an SMB file share on an AWS Storage Gateway.
  The template provisions an S3 bucket, an IAM role for bucket access,
  and an SMB file share resource on an existing Storage Gateway.

Parameters:
  GatewayARN:
    Description: "ARN of the pre-activated Storage Gateway"
    Type: String
  S3BucketName:
    Description: "Name of the S3 bucket to use as backend for the file share"
    Type: String

Resources:
  FileShareBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

  FileShareRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - storagegateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: StorageGatewayFileSharePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: !GetAtt FileShareBucket.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub "${FileShareBucket.Arn}/*"

  MySMBFileShare:
    Type: AWS::StorageGateway::SMBFileShare
    Properties:
      GatewayARN: !Ref GatewayARN
      LocationARN: !GetAtt FileShareBucket.Arn
      Role: !GetAtt FileShareRole.Arn
      DefaultStorageClass: S3_STANDARD
      ObjectACL: private

Outputs:
  SMBFileShareARN:
    Description: "ARN of the created SMB File Share"
    Value: !GetAtt MySMBFileShare.FileShareARN
