AWSTemplateFormatVersion: "2010-09-09"

Description: "CloudFormation template to create an SMB file share on an AWS Storage Gateway."

Parameters:
  GatewayARN:
    Description: "ARN of the pre-activated Storage Gateway"
    Type: String

  S3BucketName:
    Description: "Name of the S3 bucket to use as backend for the file share"
    Type: String

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName

  IAMRoleForStorageGateway:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "StorageGatewaySMBRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "storagegateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "StorageGatewayS3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                Resource: !Sub "arn:aws:s3:::${S3BucketName}"
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"

  StorageGatewaySMBFileShare:
    Type: "AWS::StorageGateway::SMBFileShare"
    Properties:
      GatewayARN: !Ref GatewayARN
      RoleArn: !GetAtt IAMRoleForStorageGateway.Arn
      LocationARN: !GetAtt S3Bucket.Arn
      DefaultStorageClass: "S3_STANDARD"
      ObjectACL: "BucketOwnerFullControl"
      ReadOnly: false
      GuessMIMETypeEnabled: true
      ValidUserList:
        - "DOMAIN\\Administrator"
      SMBACLEnabled: false
      Authentication: "ActiveDirectory"

Outputs:
  SMBFileShareARN:
    Description: "ARN of the created SMB File Share"
    Value: !Ref StorageGatewaySMBFileShare
