AWSTemplateFormatVersion: "2010-09-09"
Description: "Automated setup for AWS Storage Gateway and SMB File Share"

Parameters:
  GatewayARN:
    Type: String
    Description: "ARN of the pre-activated Storage Gateway (must be provided manually after activation)."

  S3BucketName:
    Type: String
    Description: "Name of the S3 bucket to use for file storage."
  
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

  IAMRoleForStorageGateway:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "StorageGatewaySMBRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "storagegateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "StorageGatewayS3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                Resource: !Sub "arn:aws:s3:::${S3BucketName}"
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"

  SMBFileShare:
    Type: AWS::StorageGateway::SMBFileShare
    Properties:
      GatewayARN: !Ref GatewayARN
      RoleArn: !GetAtt IAMRoleForStorageGateway.Arn
      LocationARN: !Sub "arn:aws:s3:::${S3BucketName}"
      DefaultStorageClass: "S3_STANDARD"
      ObjectACL: "BucketOwnerFullControl"
      ReadOnly: false
      GuessMIMETypeEnabled: true
      ValidUserList:
        - "DOMAIN\\Administrator"
      SMBACLEnabled: false
      Authentication: "ActiveDirectory"

Outputs:
  S3Bucket:
    Description: "S3 Bucket created for storage"
    Value: !Ref S3Bucket

  StorageGatewayRole:
    Description: "IAM Role created for Storage Gateway"
    Value: !GetAtt IAMRoleForStorageGateway.Arn

  SMBFileShareARN:
    Description: "ARN of the created SMB File Share"
    Value: !Ref SMBFileShare
